Lab 4 Exercises
===============
_Note, there is no bonus problem this week, but I will award 1 extra point if I think your analysis in problem 1 or 3 goes above and beyond what is required._

In [3]:
# import the libraries that we need
# once your run this cell, use cities
# to access the GeoDataFrame, make a copy()
# and you should only have to include this code one time
# in your notebook

!pip install mapclassify -q
import pandas as pd
import geopandas as gpd
from IPython.display import display, HTML, Markdown as md
import xyzservices.providers as xyz
import folium
import matplotlib.pyplot as plt
from matplotlib import colors
# load the URL into a geopandas GeoDataFrame
url = "https://github.com/mcuringa/cartopy/raw/main/notebooks/data/us-city-demographics.geojson"
cities = gpd.read_file(url)
cities.sample(5)

,city,state,total_pop,median_inc,asian,black,indian,latino,mixed,other,pacific,white,poverty,pop_change,inc_change,area,geometry
212,North Las Vegas,NV,264022,71774,17027,55905,806,111363,13747,1126,1895,62153,31179,29633.0,15946.0,105.318166,POINT (-115.08918 36.28987)
118,Fort Lauderdale,FL,182673,75376,2688,52868,285,36082,6314,958,51,83427,26923,5498.0,23061.0,34.581453,POINT (-80.14673 26.14123)
198,St. Paul,MN,308806,69919,56453,47538,1552,26534,17261,1018,73,158377,50170,7986.0,17078.0,51.972292,POINT (-93.10406 44.9489)
48,Jurupa Valley,CA,105672,91562,4686,3427,102,76033,1453,122,247,19602,10797,3470.0,28276.0,42.939979,POINT (-117.46761 34.00259)
328,Seattle,WA,734603,116068,122860,48754,2876,54855,50495,3678,1550,449535,72176,46358.0,36503.0,83.999945,POINT (-122.35154 47.61934)

In [4]:
# in case you want to use base_map
def base_map(center=None, zoom=5, provider=xyz.CartoDB.Positron, name="US Cities"):
    """
    Create a base map using Folium.

    Parameters:
    - center: [latitude, longitude] for the center of the map
    - zoom: Initial zoom level of the map, scale is 1-18 (zoomed out --> zoomed in)
    - provider: Map tile provider from xyzservices (e.g., xyz.CartoDB.Positron, xyz.CartoDB.DarkMatter, etc.)
    - name: Name of the map (will show up if Layer Control is added)

    Returns:
    - folium.Map object
    """
    # if no center is provided, center it near the middle of the US
    if center == None:
        center = [37.886, -97.232]

    # check the range on our zoom level
    if zoom < 1 or zoom > 18:
        zoom = 5

    m = folium.Map(name="name", tiles=provider,
                   attr=provider.attribution, location=center, zoom_start=zoom)
    return m

Problem 1: explore demographics
-------------------------------
This week we added new fields to our
city data set that descibe the racial/ethnic
demographics of the city, along with some
economic information.

Using the techniques we have learned so far,
so as filtering data, calculating new columns,
and using functions on columns like `mean()`,
`sum()`, `max()`, `min()` and `count()`.

1. Create a Markdown cell that presents your findings.
   - give it a header
   - you can "hardcode" any data needed
   - describe what your code does
2. Create a code cell that shows how your explore the data.
   It should display at least one table of data and
   at least one f-string that mixes mardkown and variables.
3. Add more code blocks or markdown blocks as needed to make a nice, brief report.

Title of your mini report
=========================

**Lorem ipsum dolor** sit amet, consectetur adipiscing elit.
Sed non risus. Suspendisse lectus tortor, dignissim sit amet.

In [ ]:
# write the code for problem 1 here

Problem 2: improve lab 4 maps
-----------------------------

Choose _one of_ the maps from [lab 4](https://colab.research.google.com/drive/1i5DIOc9NVH0ek1SkVCbcRaLoJItpxBJ5?usp=sharing). Get it working in your Notebook. Modify the following things on the map:

- change the colormap
- improve the title
- add or improve the tooltip
- add or improve the popup

In [1]:
# problem 2 code here

Problem 3: make your own colormap
---------------------------------
Using what you learned in problem 2, create your own colormap which plots a different set of data
onto a map. Include a tooltip and popup for your data points. Include a markdown
title block, either as a markdown cell before your code or as a markdown display in your code.

You _don't_ have to include a legend, but you can if you want to.


Title of your map
=================

**Lorem ipsum dolor** sit amet, consectetur adipiscing elit.
Sed non risus. Suspendisse lectus tortor, dignissim sit amet.

In [ ]:
# code for problem 3 here